### ISSUE TITLE
[Feature Request] Nested Tasks

### ISSUE THREAD

**Issue by rapatel0** [thingnotok/obsidian-toggle-list#6] opened 2022-11-01 00:41 UTC
Would like the ability to toggle tasks that are subtasks or nested within lists. 

Example:
```
- [ ] Task with a subtask
    - [ ]  Task that cannot be toggled via a state group
- List with a subtask
    - [ ]  Task that cannot be toggled via a state group
```

**Comment by thingnotok** [comment] 2022-11-01 01:44
Hi, thanks for your proposal. 

Do you mean the children lines follow their parent's state when parent is toggled?
For example, the task list
``` 
- [ ] Parent line
    - [ ] child 1
    - [x] child 2
```
changes to the following when the parent line is toggled.
```
- [x] Parent line
    - [x] child 1
    - [x] child 2
```

In current design, each line toggles separately, according to their current state and the triggered state group. 

I'm not sure if it's a good idea to do so. It would be nice to automatically mark all subtasks finished when the parent task is toggled. But won't that be annoying if all subtasks are marked unchecked when parent is toggled again?  Or which state should the subtasks toggle to when the parent is going back to paragraph or list? It's possible to do so, but that will need to add some special rules for task group, and may even need to record tasks' previous states to avoid confusing scenarios. 

Can you elaborate more on your system's task management (including state groups) and how you plan to use this feature? It would be great to listen more advices before I start the new design. 😃

**Comment by rapatel0** [comment] 2022-11-01 01:49
> In current design, each line toggles separately, according to their current state and the triggered state group.

This would be ideal. Each sub task should be independent. 

> Can you elaborate more on your system's task management (including state groups) and how you plan to use this feature?

For each meeting, i have a list of actions for follow up that come out of it. I then use a workflow to toggle these follow ups based on the state group. 

I also break down tasks into subtasks for larger projects. In these subtasks. It's helpful to work through the list of subtasks independently after they are broken down. 

I don't have a need for linking state between parent and child tasks. this would likely cause problems in my workflow

**Comment by thingnotok** [comment] 2022-11-01 01:57
Thanks for the clarification.  I believe the current release can fulfill your need.

You can toggle all lines by first selecting them (hold shift and move the cursor with ⬆️/⬇️ or with mouse) and triggering the toggle action either by commands or hotkeys. 

Let me know if anything is not clear ! 😀

**Comment by rapatel0** [comment] 2022-11-03 11:43
Doesn't work for me 

This is a recording of me toggling a list from the top level to a nested level without it working. I'm toggling the same hotkey at both levels of the list but it doesn't work when the bullet is nested. It just stops

![Recording 2022-11-03 at 06 42 24](https://user-images.githubusercontent.com/18704704/199712093-029c2604-cba6-4483-a92a-b0c2d3545084.gif)

**Comment by thingnotok** [comment] 2022-11-03 12:18
Ok, now I  finally understand what the problem is. I’ll look into it ! And try to fix it tonight

**Comment by thingnotok** [comment] 2022-11-03 12:52
Hi here's a record of me trying to reproduce your problem.  The task toggling under a list seems to work in my environment.  

Can you record another on with the Devtools open so I can debug what's happening? 
You can open it with Obsidian > View > Toggle Developer Tools, or Ctrl + Shift + I (Win/Linux), Option + Cmd + I (macOS)

https://user-images.githubusercontent.com/29173832/199724227-f059e772-1cd1-4e36-935c-047e90391066.mov

**Comment by thingnotok** [comment] 2022-11-03 12:57
If you're available in the next hour, maybe we can discuss on the issue through google chat in gmail: thingnotok at gmail.com. The iteration would be faster.

**Comment by clydebaron2000** [comment] 2022-11-03 21:32
i also have this problem. note that the cycling through states (by the plugin itself, not any other plugin) is the problem here ane not merely checking an item off. 
additionally, tasks/bullets should retain their indentation upon change.

**Comment by clydebaron2000** [comment] 2022-11-03 21:38
a quick fix of this problem would be changing this line in main.ts to not just look at the begining of the line and then the prefix, but also any whitespace characters ie:
```diff
- let state_regex = new RegExp(`^${prefix}(.*)${suffix}$`);
+ let state_regex = new RegExp(`^(\s*)${prefix}(.*)${suffix}$`);
```
if \s is interpreted as any whitespace character, just remember you have to capture it so you can output it back out to the editor

**Comment by thingnotok** [comment] 2022-11-04 04:54
@clydebaron2000 Hi, thanks to you reply. Are you using space for indentation? The plugin currently only support tabs as indentation. But if you keep a blank state in the group, it can still treat line with spaces and normal text and add prefix before the spaces.

I design not to have spaces before prefix to make it simple. But maybe I'll add support for spaces indentation in the future. 

Apart from the spaces, I still can't reproduce your problems. I can still toggle states for line with leading spaces (not treated as indentation). Can you share your environment and the data.json under the plugin folder with me? I think I need to reproduce your problems first to fix them.

**Comment by thingnotok** [comment] 2022-11-04 15:25
@clydebaron2000  Thanks to your suggestion. and also @rapatel0 's help. I just finished the support for space indentation. Please let me know if this fix works for you. 
Just replace the main.js in plugin folder with the attachment.
https://drive.google.com/file/d/1Xu4HZHio638CmCZlM3b_Xn27IftcBir5/view?usp=share_link

**Comment by clydebaron2000** [comment] 2022-11-04 16:22
i think you should enable both, since a) it may be unintuitive to people who have a tab-space substituter why things are not working and b) it is really a simple change in regex. [Below is a simple demonstration of the replace command](https://regexr.com/71lsd). Note that the `m` (multiline) flag must be enabled.
![image](https://user-images.githubusercontent.com/20262899/200025571-fff0997b-ad5e-42aa-bcbb-da27bd92492a.png)

**Comment by thingnotok** [comment] 2022-11-04 17:18
@clydebaron2000 yeah, that' s what I'm doing. The current fix use "(\s*)" to match leading spaces or tabs instead of counting indents, (and the matched indents "(\s*)" are added back after changing state). Is the attached js not working on tabs for you?

**Comment by clydebaron2000** [comment] 2022-11-05 00:42
are you saying you are not going to add this in the release? I will modify my existing JS on my end but i don't want the behavior to revert back when I auto-update.

**Comment by thingnotok** [comment] 2022-11-05 00:44
haha by next release, I mean the current to fix this issue. I just want to make sure it work for you and @rapatel0  before I release it.

**Comment by rapatel0** [comment] 2022-11-05 19:16
No dice. It's not applying the change correctly

![Recording 2022-11-05 at 14 15 59](https://user-images.githubusercontent.com/18704704/200137145-6774e844-dbbd-421a-95f1-6e0d380ea790.gif)

**Comment by thingnotok** [comment] 2022-11-06 03:58
Hey @rapatel0 I try to reproduce this with your data json yesterday.
Here's what I got.  

https://user-images.githubusercontent.com/29173832/200153055-a3bf7e08-2146-44b0-8a6f-7a375768797a.mov

The behavior in your example seems like the previous implementation. [The provided js in last reply](https://github.com/thingnotok/obsidian-toggle-list/issues/6#issuecomment-1303760478) does record raw text, leading space, and the matched state. It would be helpful if you can share the console log with me, thank you!

![image](https://user-images.githubusercontent.com/29173832/200153292-5dedec23-76b5-47cb-b82d-4f6f477e039d.png)
The first line is the matching result: [input text, leading spaces, raw text], and the second line record raw text and matched state. The rest logs are for cursor relocation purpose.

**Comment by rapatel0** [comment] 2022-11-06 14:19
It's working! 

I must have forgotten to restart obsidian with the previous try. Awesome!

**Comment by thingnotok** [comment] 2022-11-08 05:28
The feature/bug is resolved in the latest release.

**Closed as completed by thingnotok** 2022-11-08 05:28 UTC
Labels: enhancement
